# Generated by Django 3.0.7 on 2020-06-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0002_auto_20200614_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=5),
            preserve_default=False,
        ),
    ]
