# Generated by Django 3.0.7 on 2020-08-09 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0004_auto_20200614_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='honoree',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 22, 56, 13, 241490)),
        ),
    ]
