# Generated by Django 3.0.7 on 2020-08-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0007_auto_20200809_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honoree',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
